<h4>New User</h4>
<style>
form{
    width:50%;
    margin: auto;
    padding: 5px;
    box-sizing: border-box;
}
form>div{
    margin-bottom: 2px;
}
label{
    display: inline-block;
    width:30%;
}
input{
    /*border-left: 0;
    border-right: 0;*/
    display: inline-block;
    width: 68%;
    box-sizing: border-box;

}
    input[type='submit']{
       width: 70%;
        border: 4px;
       margin-left: 30%;
        display: block;
    }
</style>

<div>
    <p>Add a new.</p>
<div></div>
    <form method="post" action="/newfriend">
        <div>
            <label for="fn">First name</label>
            <input type="text" id="fn" name="first_name">
        </div>

        <div>
            <label for="ln"> Last name </label>
            <input type="text" id="ln" name="last_name">
        </div>



        <div>
            <label for="sex">Gender </label>
            <select id="sex" name="sex">
                <option value="m" selected>Male</option>
                <option value="f">Female</option>
            </select>

        </div>

        <div>
            <label for="age">Age </label>
            <input type="text" id="age" name="age">
        </div>

        <input type="submit" value="save">
    </form>

</div>