<header>

    <nav>
        <ul>
            <li> <a href="<?php echo Functions::createLink('/');?>">Home</a> </li>
            <li> <a href="<?php echo Functions::createLink('about');?>">About</a> </li>
            <li> <a href="<?php echo Functions::createLink('contact');?>">Contact</a> </li>
            <li style="float: right;"> <a href="<?php echo Functions::createLink('test');?>">Test</a> </li>

            <li style="float: right;">
                <?php if($session->is_logged_in()){ ?>
                    Hi <?php echo $_SESSION['username'];?>
                    <a href="<?php echo Functions::createLink('logout');?>"> Logout</a>
                <?php }else{?>
                    <a href="<?php echo Functions::createLink('login');?>">Login</a>
                <?php }?>
            </li>
        </ul>
    </nav>

    <h1>Layout </h1>

</header>