<?php
#require_once '../classes/init.class.php';


?>
<html>
<head>
    <title>Layout</title>
    <meta>
    <link type="text/css" rel="stylesheet" href="/css/style.css">
    <link type="text/css" rel="stylesheet" href="/css/home.css">
    <style>

    </style>

</head>

<body>
    <?php
    /** @noinspection PhpIncludeInspection */
    !$this->header? :include_once TEMPLATES.DS.'header.phtml';


    if($this->main_is_file){
        /** @noinspection PhpIncludeInspection */
        require_once VIEWS.DS.$this->view_name.'.phtml';
    }else{
        echo $this->view_name;
    }


    /** @noinspection PhpIncludeInspection */
    !$this->footer? :include_once TEMPLATES.DS.'footer.phtml';
    ?>
</body>

<script type="text/javascript" src="/js/script.js"></script>
<script type="text/javascript">



</script>
</html>